### ISSUE TITLE
Problem of connection to the AP

### ISSUE THREAD

**Issue by BGM00000** [joelsernamoreno/EvilCrowCable-Wind#2]
Hello, first of all I would like to say that you have done a great job and wish you all the best, I have a small problem, I have successfully flashed the firmware on my cable without problem, I've changed the SSID and password for my connection share (I tested with and without the ‘Maximise compatibility’ option in the settings (SSID = ‘iPhone de Thomas’) but when I plug in the cable I get the impression that it can't connect to my access point and when I go to http: //cable-wind. local/ the page loads continuously, I'd like to find its IP but I don't know how to do it on IOS (I've already tried flashing the firmware to 1.0 to see if that would fix the problem). Also, after flashing the firmware and removing the magnet when I plug it in, it appears as ESP32 dev in the device settings. Thank you for your help in advance!

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

Do not use firmware v1.0, there is a problem with USB stability, use firmware v1.1 (this is fixed here)

I have never test AP with iphone and Evil Crow Cable Wind, I will test this and give you a solution

**Comment by BGM00000** [comment]
Ok, really thank you so much for your work, I think a lot of people must have told you that, but really THANK YOU! 

Here's a video of my problem : **https://drive.google.com/file/d/1VnZt2vZOrN475KJtiJPI8cJ94dyDzq07/view?usp=sharing**

**Comment by BGM00000** [comment]
There might be something to change in the code so that it can be connected to an iPhone, or else switch it to AP mode so that it can create its own wifi (like the OMG cable) (these are just suggestions, I can't imagine how much work it must be).

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

I set up your environment with this:

- Arduino IDE version: 2.3.4
- ESP32 by Espressif Systems: 3.0.7

I've flashed the latest firmware version (v1.1)

On iPhone I have changed the SSID here: Settings -> General -> Information -> Name: Evil Crow Cable Wind (check my image)

![5980888276787119234](https://github.com/user-attachments/assets/8fa6a11b-b48c-44ba-9dcb-f95782ba6e06)

In the AP settings, I have set the password: 123456789

I have connected the cable and it has automatically connected to my Wi-Fi AP (check the connection icon in my dynamic island):

![5980888276787119241](https://github.com/user-attachments/assets/d23c08a0-0d8e-4db9-b75b-4dd789dae62a)

Finally, I opened safari and accessed http://cable-wind.local/

![5980888276787119242](https://github.com/user-attachments/assets/dfd5e2fa-6070-45bf-bac5-6f2bb3ee6df1)

I didn't have to modify the firmware, I just followed the steps in the repository. I think you have received a defective device

Can you run the command **dmesg -w** and connect the cable to the computer? You should see something like this:

![dmesg](https://github.com/user-attachments/assets/bd51f1ae-ed27-40ca-a6b3-45b9bb1af096)

Can you confirm that you changed the iPhone SSID in the same way I did?: **Settings -> General -> Information -> Name: Evil Crow Cable Wind**

I see a bit strange what it says in your personal access point configuration. In your AP information it says the following: << Evil Crow Cable Wind >>. In my case it says “Evil Crow Cable Wind”. Make sure the SSID is spelled correctly, check my last image:

![5980888276787119251](https://github.com/user-attachments/assets/c490fcbb-f9b5-4cd5-81f9-e121cb5a6f2f)

**Comment by BGM00000** [comment]
_Hi, thanks for the reply, so here's what you asked me to do:_ https://drive.google.com/file/d/1M8Rs43BckuVShcM9E_ABVzB_bDXfhBrw/view?usp=sharing

(and yes I did everything right and tried again, I even tried on another computer)

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

Thanks for your comment!

I'll take this opportunity to answer your question about Evil Crow Cable Wind being in charge of managing a wifi access point like OMG Cable

The problem is that the ESP32-S3 inside Evil Crow Cable Wind gets very hot if I program the firmware for a wifi access point (ESP32-S3 reaches +90 degrees). If the firmware is station mode and you are the one managing the WiFi access point, the Evil Crow Cable Wind does not get as hot

**Comment by BGM00000** [comment]
Oh ok thanks now i understand

**Comment by joelsernamoreno** [comment]
Hi @BGM00000 

Check your mail, you must have received an email from april brother

**Comment by BGM00000** [comment]
Yes perfect I received and answered

**Comment by BGM00000** [comment]
Perfect! I've just received the tracking number for the replacement, but I had a few questions: when I receive it, do I have to plug it in once and then unplug it and flash it, or can I flash it directly? And do I have to leave the magnet on for the whole flash or just when I plug it in? Does the cable try to connect in a loop or is there a time limit or number of tries?

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

You should receive the cable with version 1.1 installed. Possibly when you connect the cable for the first time, this will be identified as flashing mode. If this happens, disconnect the cable and reconnect it. Check with dmesg -w that the cable is identified as a keyboard and not only as a serial port

The firmware is configured not to advance until it connects to the wifi access point. There is no number of attempts, example: the web panel does not start until the cable is connected to the wifi access point

If you need to flash the firmware, you just use the magnet to connect the cable to the computer. You can check that the cable is in flash mode by using dmesg -w. You will see that the cable is identified only as a serial port and not as a keyboard. There is a picture of this in the repository documentation. You can remove the magnet during firmware flashing after connecting the cable in flash mode to the computer

Let me know if you have other questions

**Comment by BGM00000** [comment]
Hi, I've just received the cable, as soon as I plugged it in it connected directly to my phone and the web interface works perfectly! Thanks a lot for your help!

**Comment by joelsernamoreno** [comment]
Hi @BGM00000 

Well, let me know if you have any other problems 😀

**Comment by BGM00000** [comment]
A few questions: is it possible to change the firmware manually so that the default language is French? Because when I change the layout in ‘config’ it's not applied correctly because the ‘GuiR’ command makes a screenshot.

**Comment by BGM00000** [comment]
OK, I've managed to modify the firmware manually, there's just one small problem when I change the ‘USB configuration’ the cable restarts fine but the name remains ‘ESP32S3_DEV’.

**Comment by BGM00000** [comment]
Do you think it's possible to manually change the usb configuration? Because it still doesn't change its name after applying the changes.

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

Are you using the correct configuration? In the repository documentation there is an example configuration that should work. Have you tested this?

**Comment by BGM00000** [comment]
I try like that:

Manufacturer : HP, Inc
Product name : Elite Keyboard
PID : 0x34A
VID : 0x3F0

The cable restarts fine but the name remains "ESP32S3_DEV" and the vid and pid do not change, even though it says "succesfull".

**Comment by joelsernamoreno** [comment]
I won't have a cable for another two weeks, but I'll try this on an ESP32-S3 board tomorrow. Maybe the USB configuration is broken with the last update

**Comment by BGM00000** [comment]
Ok thank you very much, I don't think my cable is faulty as everything else is working.

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

I have tested this and there is a problem in the firmware. I will fix this when I receive the cable

**Comment by BGM00000** [comment]
ok no worries thanks for the reply

**Comment by BGM00000** [comment]
Hi, just wondering, when is the next update coming out?

**Comment by joelsernamoreno** [comment]
Hello @BGM00000 

USB config fixed. Use **v1.1.1**

Let me know if you find other bugs

Thanks

**Comment by BGM00000** [comment]
Ok perfect it works , maybe you could make a variable just below the wifi name and password in the firmware.ino file where we can put the default keyboard layout at launch , ( example : “String layout = ‘fr_fr’ )
